# Generated by Django 3.0.2 on 2020-01-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmodel',
            name='review_content',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
