# Generated by Django 3.0.2 on 2020-01-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200129_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmodel',
            name='review_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
